### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by jayqi** [uptake/pkgnet#267]
I've begun working on a Python implementation of pkgnet. 🎉 

Branch is here: https://github.com/jayqi/pkgnet/tree/py-pkg/py-pkg

This issue will track progress and discussion on design decisions. 

Some code standards decisions to make:

- [ ] **Linter**: Currently using flake8, [link to config](https://github.com/jayqi/pkgnet/blob/py-pkg/py-pkg/setup.cfg)
- [ ] **Formatter**: Currently using black, [link to config](https://github.com/jayqi/pkgnet/blob/py-pkg/py-pkg/pyproject.toml)
- [ ] **Line length**: Currently using black's default of 88 characters
- [ ] **Minimum Python version**: Currently 3.6, because I'm using f-strings.
- [ ] **Docstring style**: Currently using Google

**Comment by jayqi** [comment]
What I have implemented as of now:

- Working node and edge extraction for DependencyReporter
- Working node and edge extraction for InheritanceReporter
- Working node and edge extraction for a new reporter, ModuleReporter, since Python has the concept of modules (R does not)
- Working implementation of DirectedGraph that uses networkx backend
    - Question: do we want to stick with networkx (which is more popular) or switch to igraph (which is what R package uses)?

Some open areas that seem so far to be pretty hard to me:

- How to parse Python code for symbolic references for FunctionReporter
- How to implement test packages for unit tests
- How do we want to generate a report? Some potential options:
    - Simple HTML template, use jinja2
    - Use Jupyter notebooks and nbconvert
- Which network viz library? Static image or interactive javascript? Some options I was looking at:
    - [pyvis](https://pyvis.readthedocs.io/en/latest/index.html) uses vis.js which is what visNetwork in R is using
    - [plotly](https://plot.ly/python/network-graphs/) example doesn't let you drag nodes, may need to dig into options further
    - [py2cytoscape](https://py2cytoscape.readthedocs.io/en/latest/) uses cytoscape.js

**Comment by jameslamb** [comment]
> How do we want to generate a report? Some potential options:
Simple HTML template, use jinja2
Use Jupyter notebooks and nbconvert

I personally prefer HTML + jinja2. `jupyter` and  `nbconvert` are ubiquitous, but also kind of heavy for what we want to do.

**Comment by jameslamb** [comment]
I'm ok with all of the "standards to discuss" things. I personally prefer line length 100 but not something I'm going to fight hard on.

I think I could do "How to implement test packages for unit tests". I had to do that for `doppel-cli` (https://github.com/jameslamb/doppel-cli/tree/master/integration_tests/test-packages/python)

**Comment by jameslamb** [comment]
I like `pyvis` for consistency with the R package. Then we can live or die with `vis.js`, and maybe even discover things in it that we can fix or open issues for.

**Comment by bburns632** [comment]
On networkx vs igraph, does igraph have a very similar API in python and
R?  We don't do all too much with graph metrics at the moment, but if we
ever do, maybe a similar API would make parity easier.

**Comment by jayqi** [comment]
> I'm ok with all of the "standards to discuss" things. I personally prefer line length 100 but not something I'm going to fight hard on.

100 length sounds good to me.

> I personally prefer HTML + jinja2. jupyter and nbconvert are ubiquitous, but also kind of heavy for what we want to do.

I agree. I think this is right level to make that tradeoff for what we need. 

> I like pyvis for consistency with the R package. Then we can live or die with vis.js, and maybe even discover things in it that we can fix or open issues for.

I'm thinking about putting the viz backend in a separate class to make it easier to replace it later. (This was also something I was thinking about doing for R.) I'll start with pyvis. 

> On networkx vs igraph, does igraph have a very similar API in python and
R?  We don't do all too much with graph metrics at the moment, but if we
ever do, maybe a similar API would make parity easier.

Sort of. It looks like the Python version has these enormous graph classes with a bajillion methods. The R implementation was completely functional. In that way the APIs are pretty different. The parameters are similar though, probably because everything uses the same C++ underneath. Here is an example:

- https://igraph.org/python/doc/igraph.GraphBase-class.html#betweenness
- https://igraph.org/r/doc/centr_betw.html

Something to consider:

- https://github.com/networkx/networkx 6.9k stars
- https://github.com/igraph/python-igraph 591 stars

**Comment by jayqi** [comment]
So the really annoying thing, and maybe deal-breaker, with pyvis is that they don't actually output code you can easily embed in an HTML doc. They have their own HTML document template where they use jinja2 to inject data into the raw javascript code to draw the graph. 

https://github.com/WestHealth/pyvis/blob/master/pyvis/templates/template.html

In order to use this, we'd have to copy-paste their javascript code block into our templates.

**Comment by jayqi** [comment]
I'm thinking now that it may be most straightforward to just write the visualization code directly in javascript, and just inject the network data as json. This might actually be the most flexible, because we don't have to worry about existence or support of a Python interface. Which don't seen to exist in general anyways. Tt doesn't seem like there are as many good options to have Python generate the javascript code -- there isn't the same htmlwidget ecosystem that R has, as far as I can tell.

**Comment by jameslamb** [comment]
> I'm thinking now that it may be most straightforward to just write the visualization code directly in javascript, and just inject the network data as json. This might actually be the most flexible, because we don't have to worry about existence or support of a Python interface. Which don't seen to exist in general anyways. Tt doesn't seem like there are as many good options to have Python generate the javascript code -- there isn't the same htmlwidget ecosystem that R has, as far as I can tell.

ok I like this! I think it makes a lot of sense, gives us a clearer path for "language 3", and (selfishly) is an opportunity for us to practice a little JS

**Comment by jayqi** [comment]
Making some progress!

![screencapture-file-Users-Jay-Desktop-pkgnet-tmp-html-2020-02-23-22_21_52](https://user-images.githubusercontent.com/2721979/75132225-030f5200-568b-11ea-8850-6475348234bb.png)

**Comment by jayqi** [comment]
Not too much work to implement a different library. This is [sigma.js](http://sigmajs.org/). 
![screencapture-file-Users-Jay-Desktop-pkgnet-tmp-html-2020-02-23-22_21_52](https://user-images.githubusercontent.com/2721979/75164099-1e06b400-56d5-11ea-8525-f68ab01f4568.png)

**Comment by jayqi** [comment]
Not too much work to implement a different library. This is [sigma.js](http://sigmajs.org/). 
![screencapture-file-Users-Jay-Desktop-pkgnet-tmp-html-2020-02-24-07_12_57](https://user-images.githubusercontent.com/2721979/75164229-51e1d980-56d5-11ea-80b0-2de24cb88d3b.png)

**Comment by jayqi** [comment]
So I've got a working implementation in place for the most part. Wondering if I should open a pull request. At some point it might be easier to start making issues for smaller pieces of stuff and tackling them individually.

**Comment by jameslamb** [comment]
> So I've got a working implementation in place for the most part. Wondering if I should open a pull request. At some point it might be easier to start making issues for smaller pieces of stuff and tackling them individually.

@jayqi I definitely think you should open a PR! I propose that you open the PR and we only focus on resolving comments related to the API, then worry about which viz library, how to the weird "package name you install is different from the one you import" thing, and other issues later.

**Comment by nicolasfguillaume** [comment]
Hi @jayqi, thanks for your great work! 

After successfully installing the package, I am trying to replicate your example but this does not work for me (Python 3.7.5 on Windows 10):

```bash
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkgnet import create_package_report
>>> create_package_report("jinja2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LC5992\Documents\MobaXterm\home\workspace\pkgnet\py-pkg\pkgnet\package_report.py", line 172, in create_package_report
    pkg_reporters = default_reporters()
  File "C:\Users\LC5992\Documents\MobaXterm\home\workspace\pkgnet\py-pkg\pkgnet\package_report.py", line 33, in default_reporters
    DependencyReporter(),
TypeError: Can't instantiate abstract class DependencyReporter with abstract methods network_measures
```

Any help would be greatly appreciated.

Thank you so much,

Nicolas

**Comment by jayqi** [comment]
@nicolasfguillaume Thanks for trying it out! Sorry that you had an error—it looks like I had a bug sneak in there. #281 should fix it.

**Comment by bburns632** [comment]
Now that CI is lower cost (in terms of time), I'd like to test what appetite there is to update the docs and publish to PyPy.  I feel guilty we're let this sit for years. 

LOE: 
- New docs
- New CI
- Handful of new issues after release 

How about it @jayqi @jameslamb?

**Comment by jayqi** [comment]
I haven't touched my implementation nearly 4 years. I don't know if it's really ready for users (I vaguely recall some stuff was still kind of janky), and I'm not sure I want to commit to developing/maintaining it.

**Comment by jameslamb** [comment]
+1 I can't to commit to supporting the Python version.

In my opinion, you or @jayqi should do one of the following:

* just delete that branch
* publish the code to a separate public repo with permissive license then immediately archive that repo
